### ISSUE TITLE
Is untokenized raw argument generation dataset available?

### ISSUE THREAD

**Issue by ddehun** [XinyuHua/textgen-emnlp19#3]
Hi.

Is it available to request the raw Reddit CMV corpus of your paper, since I hope to process the dataset with a different tokenizer (e.g., BPE, sentencepiece).

Thanks!

**Comment by XinyuHua** [comment]
Hi, I will try to find the untokenized version and upload it this weekend.

**Comment by XinyuHua** [comment]
The untokenized data for CMV is uploaded.

https://github.com/XinyuHua/textgen-emnlp19#dataset
